### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by AnasGhrab** [OpenEdition/OTX#1]
Bonjour,

Suivant l'INSTALL, en arrivant à : 

Créer un utilisateur:

> php install/create_user.php [username] [password]

J'obtiens

PHP Warning:  require_once(Config.php): failed to open stream: No such file or directory in OTX/OTXConfig.class.php on line 8

En effet, il n'y a pas de fichier Config.php

---

Anas

**Comment by arnaudcordier** [comment]
Oui cela fait partit des dépendances à installer, elles sont listées dans le fichier  README.md
Sur un système debian, les paquets sont : php-config, php5-json, php5-curl, php5-xsl

Le paquet php-config installera /usr/share/php/Config.php

On peut aussi l'installer avec pear : pear install config
