### ISSUE TITLE
Lacks in doc ?

### ISSUE THREAD

**Issue by flartet** [OpenEdition/OTX#2]
After uncompressing the files, problem with 
require_once('Config.php')
I had to guess I had to install pear and Config package.

Then, the create_user.php script doesn't work and doesn't display any error message, no user in DB.
Then I removed the @ in @this in the OTXConfig class and got errors with the XML_Parser module ?
Any help would be appreciated as also LODEL that I'm trying to install is really buggy.

I'm on Debian 8.

**Comment by arnaudcordier** [comment]
Dependencies are listed in the INSTALL file : https://github.com/OpenEdition/OTX/blob/master/INSTALL#L8

I would need what XML error you have. I retested an installation and create_user.php reply "User created successfully". I cannot reproduce the bug.

**Comment by flartet** [comment]
Here is the problem. I checked Debian 7 and there is php-config, but this package isn't available in Debian 8.
I think this is why I have the XML problem. I'll check the contents of the php-config on Debian 7 and compare it with the pear package.
And by the way, thanks for your quick reply.

**Comment by flartet** [comment]
Ok, that was the point I guess. I had the nice version of the message "user created".

So, on Debian 8, I installed :
$> apt-get install php-pear php-xml-parser
$> pear install Config

In the previous attempt I had installed XML_Parser with Pear, maybe it didn't like it.
